FROM golang:1.11

RUN go get golang.org/x/lint/golint

ENV GO111MODULE on

WORKDIR /go/src/discovery

COPY . .

RUN make deps && make test && make install

RUN useradd -ms /bin/sh discovery
WORKDIR /home/discovery
USER discovery

ENTRYPOINT [ "discovery" ]
