// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rds.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ListRepositoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRepositoriesRequest) Reset()         { *m = ListRepositoriesRequest{} }
func (m *ListRepositoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRepositoriesRequest) ProtoMessage()    {}
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eac9d3f8ca57de4, []int{0}
}
func (m *ListRepositoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRepositoriesRequest.Unmarshal(m, b)
}
func (m *ListRepositoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRepositoriesRequest.Marshal(b, m, deterministic)
}
func (m *ListRepositoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRepositoriesRequest.Merge(m, src)
}
func (m *ListRepositoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRepositoriesRequest.Size(m)
}
func (m *ListRepositoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRepositoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRepositoriesRequest proto.InternalMessageInfo

type ListRepositoriesResponse struct {
	Repositories         []string `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRepositoriesResponse) Reset()         { *m = ListRepositoriesResponse{} }
func (m *ListRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRepositoriesResponse) ProtoMessage()    {}
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eac9d3f8ca57de4, []int{1}
}
func (m *ListRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRepositoriesResponse.Unmarshal(m, b)
}
func (m *ListRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRepositoriesResponse.Marshal(b, m, deterministic)
}
func (m *ListRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRepositoriesResponse.Merge(m, src)
}
func (m *ListRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRepositoriesResponse.Size(m)
}
func (m *ListRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRepositoriesResponse proto.InternalMessageInfo

func (m *ListRepositoriesResponse) GetRepositories() []string {
	if m != nil {
		return m.Repositories
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRepositoriesRequest)(nil), "cloud.deps.rds.api.ListRepositoriesRequest")
	proto.RegisterType((*ListRepositoriesResponse)(nil), "cloud.deps.rds.api.ListRepositoriesResponse")
}

func init() { proto.RegisterFile("rds.proto", fileDescriptor_6eac9d3f8ca57de4) }

var fileDescriptor_6eac9d3f8ca57de4 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0xc7, 0xc9, 0xaf, 0x3f, 0xc4, 0x2e, 0x1e, 0x64, 0x3d, 0x18, 0x7b, 0x92, 0x80, 0x20, 0xa8,
	0xbb, 0xa8, 0x77, 0x0f, 0xa5, 0x47, 0x0f, 0x25, 0xde, 0x7a, 0x91, 0x6d, 0x32, 0xa4, 0x03, 0x35,
	0x33, 0xee, 0x4c, 0x2a, 0xc1, 0x9b, 0x8f, 0xa0, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0x12, 0x0d, 0x52,
	0xa9, 0x82, 0xb7, 0x99, 0xef, 0xfc, 0xfb, 0xce, 0xc7, 0x0c, 0x63, 0x29, 0x8e, 0x23, 0x29, 0x59,
	0x5b, 0x2c, 0xa9, 0x29, 0x5d, 0x09, 0x2c, 0xae, 0x53, 0x03, 0xe3, 0x68, 0x56, 0xa1, 0x2e, 0x9a,
	0xb9, 0x2b, 0xe8, 0xce, 0x57, 0x91, 0x8b, 0x33, 0x28, 0x48, 0x5a, 0x51, 0xe8, 0xd3, 0x2a, 0x28,
	0x3c, 0x84, 0xd6, 0xeb, 0x02, 0x63, 0x79, 0xcb, 0x21, 0x6a, 0xeb, 0x2b, 0xa2, 0x6a, 0x09, 0x81,
	0x51, 0xfa, 0xd0, 0x07, 0x46, 0x1f, 0xea, 0x9a, 0x34, 0x28, 0x52, 0xdd, 0xdf, 0xcb, 0x0e, 0xcc,
	0xfe, 0x35, 0x8a, 0xe6, 0xc0, 0x24, 0xa8, 0x14, 0x11, 0x24, 0x87, 0xfb, 0x06, 0x44, 0xb3, 0x2b,
	0x93, 0x6e, 0x96, 0x84, 0xa9, 0x16, 0xb0, 0x99, 0xd9, 0x89, 0x6b, 0x7a, 0x9a, 0x1c, 0x0e, 0x8e,
	0x87, 0xf9, 0x37, 0xed, 0xe2, 0x39, 0x31, 0x7b, 0x5f, 0xc3, 0xed, 0x04, 0xa5, 0xa0, 0x15, 0xc4,
	0xd6, 0x3e, 0x9a, 0xff, 0xdd, 0x5e, 0x7b, 0xe2, 0x36, 0x7f, 0x75, 0xbf, 0x98, 0x19, 0x9d, 0xfe,
	0xad, 0xf9, 0xd3, 0x5e, 0x96, 0x3e, 0xbd, 0xbe, 0xbd, 0xfc, 0xb3, 0x76, 0xd7, 0xaf, 0xce, 0xfd,
	0xba, 0xa9, 0xf1, 0x91, 0xf9, 0x81, 0xf0, 0x78, 0x3b, 0x9f, 0xdc, 0x4c, 0x3b, 0x1e, 0xd3, 0x64,
	0x36, 0x08, 0x8c, 0xf3, 0xad, 0x0f, 0x3a, 0x97, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x7d,
	0x0b, 0xe7, 0x9a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryDiscoveryClient is the client API for RepositoryDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryDiscoveryClient interface {
	List(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
}

type repositoryDiscoveryClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryDiscoveryClient(cc *grpc.ClientConn) RepositoryDiscoveryClient {
	return &repositoryDiscoveryClient{cc}
}

func (c *repositoryDiscoveryClient) List(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.rds.api.RepositoryDiscovery/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryDiscoveryServer is the server API for RepositoryDiscovery service.
type RepositoryDiscoveryServer interface {
	List(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
}

// UnimplementedRepositoryDiscoveryServer can be embedded to have forward compatible implementations.
type UnimplementedRepositoryDiscoveryServer struct {
}

func (*UnimplementedRepositoryDiscoveryServer) List(ctx context.Context, req *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterRepositoryDiscoveryServer(s *grpc.Server, srv RepositoryDiscoveryServer) {
	s.RegisterService(&_RepositoryDiscovery_serviceDesc, srv)
}

func _RepositoryDiscovery_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryDiscoveryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.rds.api.RepositoryDiscovery/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryDiscoveryServer).List(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RepositoryDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.rds.api.RepositoryDiscovery",
	HandlerType: (*RepositoryDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RepositoryDiscovery_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rds.proto",
}
